### ISSUE TITLE
Using this package, I have created a trait to support auto-generation for primary keys for Laravel 10 (string form only)

### ISSUE THREAD

**Issue by dereckmartin** [odan/tsid#1]
For anyone who wishes to make it better or use it as is. 

This uses the string form of the TSID.
https://gist.github.com/dereckmartin/06eaf720c50bb5ba1c81d83106cb7bc8

**Comment by odan** [comment]
Thanks for sharing.

1. For testing purposes, you could implement the `Odan\Tsid\TsidFactoryInterface` that generates a fixed set of predefined TSID's.

2. I would not recommend using a string as primary key in your database, because this is slow, and you need too much hacking around. As mentioned in the README, try to use a `BIGINT(20) unsigned` for the primary key.
